// web/src/components/KgReasoningChain/index.vue
<template>
  <a-collapse
    v-if="steps && steps.length > 0"
    class="kg-reasoning-chain"
    :default-active-key="defaultOpen ? ['chain'] : []"
    ghost
  >
    <a-collapse-panel key="chain" :header="`知识图谱推理过程（${steps.length} 步）`">
      <ol class="kg-reasoning-chain__list">
        <li
          v-for="(step, index) in steps"
          :key="index"
          class="kg-reasoning-chain__row"
        >
          <span class="kg-reasoning-chain__index">{{ index + 1 }}</span>
          <div class="kg-reasoning-chain__body">
            <div class="kg-reasoning-chain__tags">
              <a-tag :color="kindColor(step.kind)">{{ kindLabel(step.kind) }}</a-tag>
              <a-tag
                v-if="step.kind === 'condition' && step.satisfied !== undefined"
                :color="step.satisfied ? 'green' : 'red'"
              >{{ step.satisfied ? '满足' : '不满足' }}</a-tag>
            </div>
            <div class="kg-reasoning-chain__label">{{ step.label }}</div>
            <div
              v-if="step.kind === 'condition'"
              class="kg-reasoning-chain__condition-meta"
            >
              <span v-if="step.expected !== undefined">期望：<code>{{ step.expected }}</code></span>
              <span v-if="step.actual !== undefined">实际：<code>{{ step.actual }}</code></span>
            </div>
            <div
              v-else-if="step.detail"
              class="kg-reasoning-chain__detail"
            >{{ step.detail }}</div>
          </div>
        </li>
      </ol>
    </a-collapse-panel>
  </a-collapse>
</template>

<script lang="ts" setup>
import type { ReasoningStep, ReasoningStepKind } from '/@/types/reasoning-protocol';

interface Props {
  steps: ReasoningStep[];
  defaultOpen?: boolean;
}

withDefaults(defineProps<Props>(), { defaultOpen: false });

const KIND_LABEL_MAP: Record<ReasoningStepKind, string> = {
  record: '命中记录',
  spec: '产品规格',
  rule: '判定规则',
  condition: '条件评估',
  grade: '最终结论',
  fallback: '降级',
};

const KIND_COLOR_MAP: Record<ReasoningStepKind, string> = {
  record: 'default',
  spec: 'blue',
  rule: 'purple',
  condition: 'cyan',
  grade: 'gold',
  fallback: 'red',
};

function kindLabel(kind: ReasoningStepKind) {
  return KIND_LABEL_MAP[kind] ?? kind;
}
function kindColor(kind: ReasoningStepKind) {
  return KIND_COLOR_MAP[kind] ?? 'default';
}
</script>

<style lang="less" scoped>
.kg-reasoning-chain {
  margin-top: 12px;
  border-radius: 12px;
  background: #fafbfc;

  &__list {
    margin: 0;
    padding-left: 0;
    list-style: none;
  }

  &__row {
    display: flex;
    gap: 12px;
    padding: 8px 0 8px 12px;
    border-left: 2px solid #e2e8f0;
  }

  &__index {
    flex-shrink: 0;
    width: 22px;
    height: 22px;
    border-radius: 50%;
    background: #f1f5f9;
    color: #64748b;
    font-size: 12px;
    line-height: 22px;
    text-align: center;
    margin-top: 2px;
  }

  &__body {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  &__tags {
    display: flex;
    flex-wrap: wrap;
    gap: 4px;
  }

  &__label {
    color: #334155;
    font-size: 13px;
  }

  &__condition-meta {
    display: flex;
    gap: 16px;
    font-size: 12px;
    color: #64748b;

    code {
      background: #f1f5f9;
      padding: 1px 6px;
      border-radius: 4px;
    }
  }

  &__detail {
    font-size: 12px;
    color: #94a3b8;
  }
}
</style>

// nlq-agent/apps/web/components/chat/KgReasoningChain.tsx
"use client";

/**
 * KG 推理链折叠面板。
 *
 * 消费 services/agent-api 通过 SSE `reasoning_step` 事件 + `response_metadata`
 * 双通道下发的 ReasoningStep 列表。组件本身是受控的纯渲染：所有事件累积
 * 由父组件（NlqChatPanel）负责。
 *
 * 暂用原生 `<details>` 实现折叠（避免对未安装的 ai-elements/Reasoning 强依赖）。
 * 后续如团队 `pnpm dlx ai-elements add reasoning` 引入官方组件，可一键替换包裹层。
 * TODO(ai-elements): swap `<details>` for `<Reasoning>` from ai-elements once installed.
 */

import type { ReasoningStep } from "@nlq-agent/shared-types";

interface KgReasoningChainProps {
  steps: ReasoningStep[];
  defaultOpen?: boolean;
}

const KIND_LABELS: Record<ReasoningStep["kind"], string> = {
  record: "命中记录",
  spec: "产品规格",
  rule: "判定规则",
  condition: "条件评估",
  grade: "最终结论",
  fallback: "降级",
};

const KIND_COLORS: Record<ReasoningStep["kind"], string> = {
  record: "bg-slate-100 text-slate-700 border-slate-200",
  spec: "bg-blue-50 text-blue-700 border-blue-200",
  rule: "bg-purple-50 text-purple-700 border-purple-200",
  condition: "bg-emerald-50 text-emerald-700 border-emerald-200",
  grade: "bg-amber-50 text-amber-800 border-amber-200",
  fallback: "bg-rose-50 text-rose-700 border-rose-200",
};

function StepRow({ step, index }: { step: ReasoningStep; index: number }) {
  const tagClass = KIND_COLORS[step.kind] ?? KIND_COLORS.fallback;
  const tagLabel = KIND_LABELS[step.kind] ?? step.kind;
  const isCondition = step.kind === "condition";

  return (
    <li className="flex gap-3 border-l-2 border-slate-200 py-2 pl-3">
      <span className="mt-1 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xs font-medium text-slate-500">
        {index + 1}
      </span>
      <div className="flex-1 space-y-1">
        <div className="flex flex-wrap items-center gap-2">
          <span
            className={`inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium ${tagClass}`}
          >
            {tagLabel}
          </span>
          {isCondition && step.satisfied !== undefined && (
            <span
              className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${
                step.satisfied
                  ? "bg-emerald-100 text-emerald-700"
                  : "bg-rose-100 text-rose-700"
              }`}
            >
              {step.satisfied ? "满足" : "不满足"}
            </span>
          )}
        </div>
        <div className="text-sm text-slate-700">{step.label}</div>
        {isCondition && (
          <div className="grid grid-cols-2 gap-2 text-xs text-slate-500">
            {step.expected !== undefined && (
              <div>
                <span className="text-slate-400">期望：</span>
                <span className="font-mono text-slate-600">
                  {String(step.expected)}
                </span>
              </div>
            )}
            {step.actual !== undefined && (
              <div>
                <span className="text-slate-400">实际：</span>
                <span className="font-mono text-slate-600">
                  {String(step.actual)}
                </span>
              </div>
            )}
          </div>
        )}
        {step.detail && !isCondition && (
          <div className="text-xs text-slate-500">{step.detail}</div>
        )}
      </div>
    </li>
  );
}

export function KgReasoningChain({
  steps,
  defaultOpen = false,
}: KgReasoningChainProps) {
  if (!steps || steps.length === 0) {
    return null;
  }

  return (
    <details
      className="mt-3 rounded-xl border border-slate-200 bg-slate-50/50 px-4 py-2 text-sm"
      open={defaultOpen}
      data-testid="kg-reasoning-chain"
    >
      <summary className="cursor-pointer select-none py-1 text-sm font-medium text-slate-600 outline-none">
        知识图谱推理过程（{steps.length} 步）
      </summary>
      <ol className="mt-2 space-y-1">
        {steps.map((step, index) => (
          <StepRow key={index} step={step} index={index} />
        ))}
      </ol>
    </details>
  );
}

export default KgReasoningChain;
